---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse

  - src: https://github.com/nikolay480/vector-role.git
    scm: git
    version: "0.1.2"

  - src: https://github.com/nikolay480/lighthouse-role.git
    scm: git
    version: "0.1.2"