---
- name: Install Clickhouse
  remote_user: centos
  hosts: clickhouse
  roles:
    - role: clickhouse

- name: Install Vector
  remote_user: centos
  hosts: vector
  tags: vector
  roles:
    - role: vector-role

- name: Install lighthouse
  hosts: lighthouse
  remote_user: centos
  handlers:
    - name: start_nginx
      become: true
      ansible.builtin.command: nginx
    - name: restart_nginx
      become: true
      ansible.builtin.command: "nginx -s reload"
  pre_tasks:
    - name: INSTALL NGINX | install repo epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: INSTALL NGINX | nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: start_nginx
    - name: INSTALL NGINX | config
      become: true
      ansible.builtin.template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: restart_nginx

  roles:
    - role: lighthouse-role