# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"

[sources.clickhouse_logs]
type = "file"
include = [ "/var/log/clickhouse/clickhouse-server.log" ]
read_from = "end"

# Print parsed logs to stdout
[sinks.clickhouse]
type = "clickhouse"
inputs = ["clickhouse_logs"]
database = "logs"
table = "mytable"

# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
# [api]
# enabled = true
# address = "127.0.0.1:8686"
