---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  multi_tool_port: "80"
  http_port: "9090"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Multitool Application created special for Netology</title>
    </head>
    <body>
      <h1>Hello, students of Netology!</h1>
    </body>
    </html>

