apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student-rolebinding
  namespace: netology
subjects:
- kind: User
  name: student
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: student-role
  apiGroup: rbac.authorization.k8s.io