apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: netology
  name: student-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "describe"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]