apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: busybox
          image: busybox
          ports:
          - containerPort: 80
          command: ["sh", "-c", "while true; do echo $(date) >> /data/data.txt; sleep 5; done"]
          volumeMounts:
            - mountPath: /data
              name: local-volume
              
        - name: multitool
          image: praqma/network-multitool:alpine-extra
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: local-volume
              
      volumes:
        - name: local-volume
          persistentVolumeClaim:
            claimName: my-pvc
