apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool:alpine-extra
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /share-data
              name: my-volume            
            - mountPath: /nfscsi-data
              name: other-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc2
        - name: other-volume
          persistentVolumeClaim:
            claimName: my-pvc3



