---
sources:
  my_source:
    type: file
    ignore_older_secs: 600
    include:
      - /var/log/yum.log
    read_from: beginning

sinks:
  my_sink:
    type: clickhouse
    inputs:
      - my_source
    endpoint: http://158.160.56.198:8123
    database: logs
    table: mytable

# address = "127.0.0.1:8686
# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"
