apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
spec:
  selector:
    app: my-app
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080