{
 "title": "Netology dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inspect: CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(node_load1)" },
    { "expr": "avg(node_load5)" },
    { "expr": "avg(node_load15)" }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти, %",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "Утилизация CPU ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r"
    }
   ]
  },
  {
   "title": "количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}*100"
    }
   ]
  }
 ]
}