---
clickhouse:
  hosts:
    clickhouse-1:
      ansible_host: 158.160.55.44

vector:
  hosts:
    vector-1:
      ansible_host: 158.160.39.40

lighthouse:
  hosts:
    lighthouse-1:
      ansible_host: 158.160.60.73
