all:
  hosts:
    cp1:
      ansible_host: 158.160.97.144
      ansible_user: yc-user
      ip: 10.128.0.15
      # access_ip: 158.160.118.104
      etcd_member_name: etcd1
      
    node1:
      ansible_host: 158.160.117.200
      ip: 10.128.0.26
      # access_ip: 158.160.117.200
      ansible_user: yc-user
    
    node2:
      ansible_host: 158.160.52.213
      ip: 10.128.0.30
      # access_ip: 158.160.52.213
      ansible_user: yc-user
    
    node3:
      ansible_host: 158.160.112.40
      ip: 10.128.0.5
      # access_ip: 158.160.52.213
      ansible_user: yc-user
    
    node4:
      ansible_host: 51.250.66.142
      ip: 10.128.0.19
      # access_ip: 158.160.52.213
      ansible_user: yc-user


  children:
    kube_control_plane:
      hosts:
        cp1:
  
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
  
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
