apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: busybox
          image: busybox
          ports:
          - containerPort: 80
          command: ["sh", "-c", "while true; do echo $(date) >> /shared-data/data.txt; sleep 5; done"]
          volumeMounts:
            - name: shared-data-volume
              mountPath: /shared-data
        - name: multitool
          image: praqma/network-multitool:alpine-extra
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: shared-data-volume
              mountPath: /shared-data
      volumes:
        - name: shared-data-volume
          emptyDir: {}
